# Generated by Django 4.2.7 on 2023-11-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(default='', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('alias', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='', max_length=1000)),
                ('authors', models.ManyToManyField(blank=True, to='app.author')),
                ('categories', models.ManyToManyField(blank=True, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='file')),
                ('nameStory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
        ),
    ]
