# Generated by Django 4.2.7 on 2023-11-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.comment'),
        ),
    ]
