# Generated by Django 4.2.7 on 2023-11-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='file',
            field=models.FileField(upload_to='app/templates/file'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='app/templates/image'),
        ),
    ]
