# Generated by Django 4.2.7 on 2023-11-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_chapters_file_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='nameStory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='app.story'),
        ),
    ]
