# Generated by Django 4.2.7 on 2023-11-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='read',
        ),
    ]
