# Generated by Django 4.2.7 on 2023-11-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_chapters_namestory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='nameStory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.story'),
        ),
    ]
