# Generated by Django 4.2.7 on 2023-11-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chapters_namestory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='nameStory',
            new_name='story',
        ),
    ]
