# Generated by Django 4.2.7 on 2023-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userstory_chapter_userstory_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
